name: release

on: 
  push:
    tags-ignore:
      - 'test-*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        dotnet-version: '10.0.x' # SDK Version to use.

    - run: |
        Invoke-WebRequest -OutFile Update-AssemblyInfoVersionFiles.ps1 https://gist.githubusercontent.com/lowleveldesign/663de4e0d5a071f938e6f7c82d7ca9a0/raw/Update-AssemblyInfoVersionFiles.ps1
        ./Update-AssemblyInfoVersionFiles.ps1

    # other tests require a desktop environment as they start cmd.exe and winver.exe processes
    - run: dotnet test -c release --filter "FullyQualifiedName~ProcessGovernor.Tests.Code.ProgramTests.ParseArgs"
      working-directory: ./procgov-tests

    - run: dotnet publish -c release -r win-x64 -o out
      working-directory: ./procgov

    - name: Copy artifacts
      run: |
        New-Item -Type Directory -Path artifacts
        Copy-Item -Path "procgov/out/procgov.exe" -Destination "artifacts/procgov.exe"
        Copy-Item -Path "procgov/out/procgov.pdb" -Destination "artifacts/procgov.pdb"
        Copy-Item -Path "procgov/out/procgov-lib.pdb" -Destination "artifacts/procgov-lib.pdb"

    - name: Zip binaries
      run: |
        Compress-Archive -Path "artifacts/procgov.exe" -DestinationPath "procgov.zip"

    - uses: marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1
      with:
        repo_token: "${{ secrets.WINGET_GH_TOKEN }}"
        prerelease: true
        files: |
          procgov.zip
          artifacts/*.pdb
          artifacts/*.exe

    - name: Copy the binary to Chocolatey path
      run: |
          Copy-Item artifacts\procgov.exe .choco\tools

    - run: |
        Invoke-WebRequest -OutFile Print-FileHashes.ps1 https://gist.githubusercontent.com/lowleveldesign/f1afd42662ee8dabe07cf8cbfe25e6a1/raw/Print-FileHashes.ps1
        "## procgov.exe" >> .choco\tools\VERIFICATION.txt
        ./Print-FileHashes.ps1 -FilePath .choco\tools\procgov.exe >> .choco\tools\VERIFICATION.txt

    - name: Build Chocolatey package
      run: choco pack
      working-directory: .choco

    - name: Release Chocolatey package
      run: choco push $(Resolve-Path "procgov.*.nupkg") -s https://push.chocolatey.org/ -k "$env:CHOCO_KEY"
      env:
        CHOCO_KEY: ${{ secrets.CHOCO_KEY }}
      working-directory: .choco

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: procgov
        path: artifacts/*
